sudo: required

language: python

python:
  - "2.7"

before_script:
  - sudo apt-get install python-demjson
  - sudo apt-get install libxml2-utils
  - pip install --upgrade setuptools
  - easy_install demjson
  - pip install html5lib
  - cd ../
  - git clone https://github.com/crosswalk-project/crosswalk-test-suite.git
  - cd demo-express/
  - cp -f lint.whitelist ../crosswalk-test-suite/tools/lint/

script: python ../crosswalk-test-suite/tools/lint/lint.py -r demo-express -p
